import { mutation } from "../_generated/server";
import { v } from "convex/values";
import { Id } from "../_generated/dataModel";

/**
 * Seed mutation to import real FY 2025-2026 calendar data from Excel
 *
 * Run: npx convex run functions/seedRealCalendar:importRealCalendar
 */
export const importRealCalendar = mutation({
  args: {},
  returns: v.object({
    fiscalYearId: v.id("fiscalYears"),
    physiciansCreated: v.number(),
    rotationsCreated: v.number(),
    weeksCreated: v.number(),
    masterCalendarId: v.id("masterCalendars"),
    assignmentsCreated: v.number(),
  }),
  handler: async (ctx) => {
    // Note: Auth removed for one-time seed operation

    // Physician data from Excel legend  
    const physicians = [
      { initials: "AG", firstName: "Amie", lastName: "Gamino", email: "amie.gamino@rush.edu" },
      { initials: "AK", firstName: "Akshay", lastName: "Kohli", email: "akshay.kohli@rush.edu" },
      { initials: "AT", firstName: "Abhaya", lastName: "Trivedi", email: "abhaya.trivedi@rush.edu" },
      { initials: "BM", firstName: "Babak", lastName: "Mokhlesi", email: "babak.mokhlesi@rush.edu" },
      { initials: "BS", firstName: "Brian", lastName: "Stein", email: "brian.stein@rush.edu" },
      { initials: "DPG", firstName: "David", lastName: "Gurka", email: "david.gurka@rush.edu" },
      { initials: "EC", firstName: "Elaine", lastName: "Chen", email: "elaine.chen@rush.edu" },
      { initials: "EP", firstName: "Ed", lastName: "Pickering", email: "ed.pickering@rush.edu" },
      { initials: "JCR", firstName: "JC", lastName: "Rojas", email: "jc.rojas@rush.edu" },
      { initials: "JEK", firstName: "Jessica", lastName: "Kuppy", email: "jessica.kuppy@rush.edu" },
      { initials: "JG", firstName: "Jared", lastName: "Greenberg", email: "jared.greenberg@rush.edu" },
      { initials: "JK", firstName: "James", lastName: "Katsis", email: "james.katsis@rush.edu" },
      { initials: "JN", firstName: "Julie", lastName: "Neborak", email: "julie.neborak@rush.edu" },
      { initials: "JR", firstName: "James", lastName: "Rowley", email: "james.rowley@rush.edu" },
      { initials: "KB", firstName: "Kevin", lastName: "Buell", email: "kevin.buell@rush.edu" },
      { initials: "KJ", firstName: "Kari", lastName: "Jackson", email: "kari.jackson@rush.edu" },
      { initials: "KS", firstName: "Kalli", lastName: "Sarigiannis", email: "kalli.sarigiannis@rush.edu" },
      { initials: "MS", firstName: "Meghan", lastName: "Snuckel", email: "meghan.snuckel@rush.edu" },
      { initials: "MT", firstName: "Mark", lastName: "Tancredi", email: "mark.tancredi@rush.edu" },
      { initials: "MV", firstName: "Mona", lastName: "Vashi", email: "mona.vashi@rush.edu" },
      { initials: "MY", firstName: "Mark", lastName: "Yoder", email: "mark.yoder@rush.edu" },
      { initials: "PN", firstName: "Prema", lastName: "Nanavaty", email: "prema.nanavaty@rush.edu" },
      { initials: "SF", firstName: "Sam", lastName: "Fox", email: "sam.fox@rush.edu" },
      { initials: "SP", firstName: "Shruti", lastName: "Patel", email: "shruti.patel@rush.edu" },
      { initials: "WL", firstName: "Waj", lastName: "Lodhi", email: "waj.lodhi@rush.edu" },
    ];

    // Create fiscal year
    const fiscalYearId = await ctx.db.insert("fiscalYears", {
      label: "FY 2025-2026",
      startDate: "2025-06-23",
      endDate: "2026-07-05",
      status: "published",
      requestDeadline: "2025-05-01T23:59:59Z",
    });

    // Create physicians
    const physicianIdMap = new Map<string, Id<"physicians">>();
    for (const phys of physicians) {
      const physicianId = await ctx.db.insert("physicians", {
        firstName: phys.firstName,
        lastName: phys.lastName,
        initials: phys.initials,
        email: phys.email,
        role: "physician",
        isActive: true,
      });
      physicianIdMap.set(phys.initials, physicianId);
    }

    // Rotation data
    const rotations = [
      { name: "Pulmonary Consults", abbreviation: "Pulm", cftePerWeek: 0.03, minStaff: 1, maxConsecutiveWeeks: 4, sortOrder: 1 },
      { name: "MICU 1", abbreviation: "MICU 1", cftePerWeek: 0.04, minStaff: 1, maxConsecutiveWeeks: 2, sortOrder: 2 },
      { name: "MICU 2", abbreviation: "MICU 2", cftePerWeek: 0.04, minStaff: 1, maxConsecutiveWeeks: 2, sortOrder: 3 },
      { name: "AICU", abbreviation: "AICU", cftePerWeek: 0.035, minStaff: 1, maxConsecutiveWeeks: 3, sortOrder: 4 },
      { name: "LTAC", abbreviation: "LTAC", cftePerWeek: 0.025, minStaff: 1, maxConsecutiveWeeks: 4, sortOrder: 5 },
      { name: "ROPH", abbreviation: "ROPH", cftePerWeek: 0.03, minStaff: 1, maxConsecutiveWeeks: 4, sortOrder: 6 },
      { name: "IP", abbreviation: "IP", cftePerWeek: 0.03, minStaff: 1, maxConsecutiveWeeks: 4, sortOrder: 7 },
      { name: "PFT", abbreviation: "PFT", cftePerWeek: 0.02, minStaff: 1, maxConsecutiveWeeks: 3, sortOrder: 8 },
    ];

    // Create rotations
    const rotationIdMap = new Map<string, Id<"rotations">>();
    for (const rot of rotations) {
      const rotationId = await ctx.db.insert("rotations", {
        fiscalYearId,
        name: rot.name,
        abbreviation: rot.abbreviation,
        cftePerWeek: rot.cftePerWeek,
        minStaff: rot.minStaff,
        maxConsecutiveWeeks: rot.maxConsecutiveWeeks,
        sortOrder: rot.sortOrder,
        isActive: true,
      });
      rotationIdMap.set(rot.abbreviation, rotationId);
    }

    // Week data (54 weeks)
    const weekData = [
      { weekNumber: 1, startDate: "2025-06-23", endDate: "2025-06-29" },
      { weekNumber: 2, startDate: "2025-06-30", endDate: "2025-07-06" },
      { weekNumber: 3, startDate: "2025-07-07", endDate: "2025-07-13" },
      { weekNumber: 4, startDate: "2025-07-14", endDate: "2025-07-20" },
      { weekNumber: 5, startDate: "2025-07-21", endDate: "2025-07-27" },
      { weekNumber: 6, startDate: "2025-07-28", endDate: "2025-08-03" },
      { weekNumber: 7, startDate: "2025-08-04", endDate: "2025-08-10" },
      { weekNumber: 8, startDate: "2025-08-11", endDate: "2025-08-17" },
      { weekNumber: 9, startDate: "2025-08-18", endDate: "2025-08-24" },
      { weekNumber: 10, startDate: "2025-08-25", endDate: "2025-08-31" },
      { weekNumber: 11, startDate: "2025-09-01", endDate: "2025-09-07" },
      { weekNumber: 12, startDate: "2025-09-08", endDate: "2025-09-14" },
      { weekNumber: 13, startDate: "2025-09-15", endDate: "2025-09-21" },
      { weekNumber: 14, startDate: "2025-09-22", endDate: "2025-09-28" },
      { weekNumber: 15, startDate: "2025-09-29", endDate: "2025-10-05" },
      { weekNumber: 16, startDate: "2025-10-06", endDate: "2025-10-12" },
      { weekNumber: 17, startDate: "2025-10-13", endDate: "2025-10-19" },
      { weekNumber: 18, startDate: "2025-10-20", endDate: "2025-10-26" },
      { weekNumber: 19, startDate: "2025-10-27", endDate: "2025-11-02" },
      { weekNumber: 20, startDate: "2025-11-03", endDate: "2025-11-09" },
      { weekNumber: 21, startDate: "2025-11-10", endDate: "2025-11-16" },
      { weekNumber: 22, startDate: "2025-11-17", endDate: "2025-11-23" },
      { weekNumber: 23, startDate: "2025-11-24", endDate: "2025-11-30" },
      { weekNumber: 24, startDate: "2025-12-01", endDate: "2025-12-07" },
      { weekNumber: 25, startDate: "2025-12-08", endDate: "2025-12-14" },
      { weekNumber: 26, startDate: "2025-12-15", endDate: "2025-12-21" },
      { weekNumber: 27, startDate: "2025-12-22", endDate: "2025-12-28" },
      { weekNumber: 28, startDate: "2025-12-29", endDate: "2026-01-04" },
      { weekNumber: 29, startDate: "2026-01-05", endDate: "2026-01-11" },
      { weekNumber: 30, startDate: "2026-01-12", endDate: "2026-01-18" },
      { weekNumber: 31, startDate: "2026-01-19", endDate: "2026-01-25" },
      { weekNumber: 32, startDate: "2026-01-26", endDate: "2026-02-01" },
      { weekNumber: 33, startDate: "2026-02-02", endDate: "2026-02-08" },
      { weekNumber: 34, startDate: "2026-02-09", endDate: "2026-02-15" },
      { weekNumber: 35, startDate: "2026-02-16", endDate: "2026-02-22" },
      { weekNumber: 36, startDate: "2026-02-23", endDate: "2026-03-01" },
      { weekNumber: 37, startDate: "2026-03-02", endDate: "2026-03-08" },
      { weekNumber: 38, startDate: "2026-03-09", endDate: "2026-03-15" },
      { weekNumber: 39, startDate: "2026-03-16", endDate: "2026-03-22" },
      { weekNumber: 40, startDate: "2026-03-23", endDate: "2026-03-29" },
      { weekNumber: 41, startDate: "2026-03-30", endDate: "2026-04-05" },
      { weekNumber: 42, startDate: "2026-04-06", endDate: "2026-04-12" },
      { weekNumber: 43, startDate: "2026-04-13", endDate: "2026-04-19" },
      { weekNumber: 44, startDate: "2026-04-20", endDate: "2026-04-26" },
      { weekNumber: 45, startDate: "2026-04-27", endDate: "2026-05-03" },
      { weekNumber: 46, startDate: "2026-05-04", endDate: "2026-05-10" },
      { weekNumber: 47, startDate: "2026-05-11", endDate: "2026-05-17" },
      { weekNumber: 48, startDate: "2026-05-18", endDate: "2026-05-24" },
      { weekNumber: 49, startDate: "2026-05-25", endDate: "2026-05-31" },
      { weekNumber: 50, startDate: "2026-06-01", endDate: "2026-06-07" },
      { weekNumber: 51, startDate: "2026-06-08", endDate: "2026-06-14" },
      { weekNumber: 52, startDate: "2026-06-15", endDate: "2026-06-21" },
      { weekNumber: 53, startDate: "2026-06-22", endDate: "2026-06-28" },
      { weekNumber: 54, startDate: "2026-06-29", endDate: "2026-07-05" },
    ];

    // Create weeks
    const weekIdMap = new Map<number, Id<"weeks">>();
    for (const week of weekData) {
      const weekId = await ctx.db.insert("weeks", {
        fiscalYearId,
        weekNumber: week.weekNumber,
        startDate: week.startDate,
        endDate: week.endDate,
      });
      weekIdMap.set(week.weekNumber, weekId);
    }

    // Create master calendar
    const masterCalendarId = await ctx.db.insert("masterCalendars", {
      fiscalYearId,
      version: 1,
      status: "published",
      publishedAt: Date.now(),
    });

    // Assignment data from Excel (424 assignments)
    const assignmentData = [
      { week: 1, rotation: "Pulm", physician: "SF" },
      { week: 1, rotation: "MICU 1", physician: "JEK" },
      { week: 1, rotation: "MICU 2", physician: "MV" },
      { week: 1, rotation: "AICU", physician: "JCR" },
      { week: 1, rotation: "LTAC", physician: "DPG" },
      { week: 1, rotation: "ROPH", physician: "WL" },
      { week: 1, rotation: "IP", physician: "EP" },
      { week: 1, rotation: "PFT", physician: "AT" },
      { week: 2, rotation: "Pulm", physician: "MY" },
      { week: 2, rotation: "MICU 1", physician: "BM" },
      { week: 2, rotation: "MICU 2", physician: "KJ" },
      { week: 2, rotation: "AICU", physician: "JN" },
      { week: 2, rotation: "LTAC", physician: "DPG" },
      { week: 2, rotation: "ROPH", physician: "JG" },
      { week: 2, rotation: "IP", physician: "PN" },
      { week: 2, rotation: "PFT", physician: "SF" },
      { week: 3, rotation: "Pulm", physician: "EP" },
      { week: 3, rotation: "MICU 1", physician: "AG" },
      { week: 3, rotation: "MICU 2", physician: "MV" },
      { week: 3, rotation: "AICU", physician: "PN" },
      { week: 3, rotation: "LTAC", physician: "SF" },
      { week: 3, rotation: "ROPH", physician: "JEK" },
      { week: 3, rotation: "IP", physician: "EP" },
      { week: 3, rotation: "PFT", physician: "MY" },
      { week: 4, rotation: "Pulm", physician: "KJ" },
      { week: 4, rotation: "MICU 1", physician: "JG" },
      { week: 4, rotation: "MICU 2", physician: "SP" },
      { week: 4, rotation: "AICU", physician: "JCR" },
      { week: 4, rotation: "LTAC", physician: "DPG" },
      { week: 4, rotation: "ROPH", physician: "WL" },
      { week: 4, rotation: "IP", physician: "JK" },
      { week: 4, rotation: "PFT", physician: "AT" },
      { week: 5, rotation: "Pulm", physician: "EP" },
      { week: 5, rotation: "MICU 1", physician: "JG" },
      { week: 5, rotation: "MICU 2", physician: "SF" },
      { week: 5, rotation: "AICU", physician: "JEK" },
      { week: 5, rotation: "LTAC", physician: "DPG" },
      { week: 5, rotation: "ROPH", physician: "MV" },
      { week: 5, rotation: "IP", physician: "EP" },
      { week: 5, rotation: "PFT", physician: "KJ" },
      { week: 6, rotation: "Pulm", physician: "JK" },
      { week: 6, rotation: "MICU 1", physician: "SP" },
      { week: 6, rotation: "MICU 2", physician: "BM" },
      { week: 6, rotation: "AICU", physician: "JCR" },
      { week: 6, rotation: "LTAC", physician: "PN" },
      { week: 6, rotation: "ROPH", physician: "WL" },
      { week: 6, rotation: "IP", physician: "JK" },
      { week: 6, rotation: "PFT", physician: "SF" },
      { week: 7, rotation: "Pulm", physician: "MS" },
      { week: 7, rotation: "MICU 1", physician: "AG" },
      { week: 7, rotation: "MICU 2", physician: "KJ" },
      { week: 7, rotation: "AICU", physician: "JN" },
      { week: 7, rotation: "LTAC", physician: "EC" },
      { week: 7, rotation: "ROPH", physician: "WL" },
      { week: 7, rotation: "IP", physician: "PN" },
      { week: 7, rotation: "PFT", physician: "MY" },
      { week: 8, rotation: "Pulm", physician: "MV" },
      { week: 8, rotation: "MICU 1", physician: "BM" },
      { week: 8, rotation: "MICU 2", physician: "MY" },
      { week: 8, rotation: "AICU", physician: "AK" },
      { week: 8, rotation: "LTAC", physician: "DPG" },
      { week: 8, rotation: "ROPH", physician: "JG" },
      { week: 8, rotation: "IP", physician: "EP" },
      { week: 8, rotation: "PFT", physician: "KJ" },
      { week: 9, rotation: "Pulm", physician: "JR" },
      { week: 9, rotation: "MICU 1", physician: "MT" },
      { week: 9, rotation: "MICU 2", physician: "JEK" },
      { week: 9, rotation: "AICU", physician: "BS" },
      { week: 9, rotation: "LTAC", physician: "JN" },
      { week: 9, rotation: "ROPH", physician: "WL" },
      { week: 9, rotation: "IP", physician: "PN" },
      { week: 9, rotation: "PFT", physician: "AT" },
      { week: 10, rotation: "Pulm", physician: "JK" },
      { week: 10, rotation: "MICU 1", physician: "SP" },
      { week: 10, rotation: "MICU 2", physician: "AG" },
      { week: 10, rotation: "AICU", physician: "JCR" },
      { week: 10, rotation: "LTAC", physician: "AK" },
      { week: 10, rotation: "ROPH", physician: "JG" },
      { week: 10, rotation: "IP", physician: "JK" },
      { week: 10, rotation: "PFT", physician: "MY" },
      { week: 11, rotation: "Pulm", physician: "KB" },
      { week: 11, rotation: "MICU 1", physician: "MY" },
      { week: 11, rotation: "MICU 2", physician: "MS" },
      { week: 11, rotation: "AICU", physician: "AT" },
      { week: 11, rotation: "LTAC", physician: "DPG" },
      { week: 11, rotation: "ROPH", physician: "WL" },
      { week: 11, rotation: "IP", physician: "EP" },
      { week: 11, rotation: "PFT", physician: "KJ" },
      { week: 12, rotation: "Pulm", physician: "AK" },
      { week: 12, rotation: "MICU 1", physician: "JG" },
      { week: 12, rotation: "MICU 2", physician: "JEK" },
      { week: 12, rotation: "AICU", physician: "MT" },
      { week: 12, rotation: "LTAC", physician: "JCR" },
      { week: 12, rotation: "ROPH", physician: "MV" },
      { week: 12, rotation: "IP", physician: "PN" },
      { week: 12, rotation: "PFT", physician: "AT" },
      { week: 13, rotation: "Pulm", physician: "SP" },
      { week: 13, rotation: "MICU 1", physician: "JG" },
      { week: 13, rotation: "MICU 2", physician: "JN" },
      { week: 13, rotation: "AICU", physician: "KJ" },
      { week: 13, rotation: "LTAC", physician: "DPG" },
      { week: 13, rotation: "ROPH", physician: "WL" },
      { week: 13, rotation: "IP", physician: "JK" },
      { week: 13, rotation: "PFT", physician: "MY" },
      { week: 14, rotation: "Pulm", physician: "MT" },
      { week: 14, rotation: "MICU 1", physician: "AG" },
      { week: 14, rotation: "MICU 2", physician: "JCR" },
      { week: 14, rotation: "AICU", physician: "AK" },
      { week: 14, rotation: "LTAC", physician: "DPG" },
      { week: 14, rotation: "ROPH", physician: "MS" },
      { week: 14, rotation: "IP", physician: "EP" },
      { week: 14, rotation: "PFT", physician: "KJ" },
      { week: 15, rotation: "Pulm", physician: "KS" },
      { week: 15, rotation: "MICU 1", physician: "SF" },
      { week: 15, rotation: "MICU 2", physician: "EC" },
      { week: 15, rotation: "AICU", physician: "KB" },
      { week: 15, rotation: "LTAC", physician: "JEK" },
      { week: 15, rotation: "ROPH", physician: "WL" },
      { week: 15, rotation: "IP", physician: "PN" },
      { week: 15, rotation: "PFT", physician: "AT" },
      { week: 16, rotation: "Pulm", physician: "JK" },
      { week: 16, rotation: "MICU 1", physician: "SP" },
      { week: 16, rotation: "MICU 2", physician: "AK" },
      { week: 16, rotation: "AICU", physician: "MV" },
      { week: 16, rotation: "LTAC", physician: "DPG" },
      { week: 16, rotation: "ROPH", physician: "WL" },
      { week: 16, rotation: "IP", physician: "JK" },
      { week: 16, rotation: "PFT", physician: "SF" },
      { week: 17, rotation: "Pulm", physician: "MS" },
      { week: 17, rotation: "MICU 1", physician: "KS" },
      { week: 17, rotation: "MICU 2", physician: "AG" },
      { week: 17, rotation: "AICU", physician: "JEK" },
      { week: 17, rotation: "LTAC", physician: "SF" },
      { week: 17, rotation: "ROPH", physician: "MT" },
      { week: 17, rotation: "IP", physician: "EP" },
      { week: 17, rotation: "PFT", physician: "AT" },
      { week: 18, rotation: "Pulm", physician: "AT" },
      { week: 18, rotation: "MICU 1", physician: "SP" },
      { week: 18, rotation: "MICU 2", physician: "JG" },
      { week: 18, rotation: "AICU", physician: "MV" },
      { week: 18, rotation: "LTAC", physician: "DPG" },
      { week: 18, rotation: "ROPH", physician: "WL" },
      { week: 18, rotation: "IP", physician: "PN" },
      { week: 18, rotation: "PFT", physician: "SF" },
      { week: 19, rotation: "Pulm", physician: "JR" },
      { week: 19, rotation: "MICU 1", physician: "AK" },
      { week: 19, rotation: "MICU 2", physician: "JG" },
      { week: 19, rotation: "AICU", physician: "BM" },
      { week: 19, rotation: "LTAC", physician: "KB" },
      { week: 19, rotation: "ROPH", physician: "WL" },
      { week: 19, rotation: "IP", physician: "JK" },
      { week: 19, rotation: "PFT", physician: "MY" },
      { week: 20, rotation: "Pulm", physician: "MY" },
      { week: 20, rotation: "MICU 1", physician: "JN" },
      { week: 20, rotation: "MICU 2", physician: "MT" },
      { week: 20, rotation: "AICU", physician: "EC" },
      { week: 20, rotation: "LTAC", physician: "MV" },
      { week: 20, rotation: "ROPH", physician: "JEK" },
      { week: 20, rotation: "IP", physician: "EP" },
      { week: 20, rotation: "PFT", physician: "MY" },
      { week: 21, rotation: "Pulm", physician: "SF" },
      { week: 21, rotation: "MICU 1", physician: "MS" },
      { week: 21, rotation: "MICU 2", physician: "PN" },
      { week: 21, rotation: "AICU", physician: "SP" },
      { week: 21, rotation: "LTAC", physician: "DPG" },
      { week: 21, rotation: "ROPH", physician: "WL" },
      { week: 21, rotation: "IP", physician: "PN" },
      { week: 21, rotation: "PFT", physician: "KJ" },
      { week: 22, rotation: "Pulm", physician: "MV" },
      { week: 22, rotation: "MICU 1", physician: "JEK" },
      { week: 22, rotation: "MICU 2", physician: "KS" },
      { week: 22, rotation: "AICU", physician: "AK" },
      { week: 22, rotation: "LTAC", physician: "DPG" },
      { week: 22, rotation: "ROPH", physician: "WL" },
      { week: 22, rotation: "IP", physician: "JK" },
      { week: 22, rotation: "PFT", physician: "SF" },
      { week: 23, rotation: "Pulm", physician: "EP" },
      { week: 23, rotation: "MICU 1", physician: "AG" },
      { week: 23, rotation: "MICU 2", physician: "AT" },
      { week: 23, rotation: "AICU", physician: "SF" },
      { week: 23, rotation: "LTAC", physician: "KJ" },
      { week: 23, rotation: "ROPH", physician: "JG" },
      { week: 23, rotation: "IP", physician: "EP" },
      { week: 23, rotation: "PFT", physician: "MY" },
      { week: 24, rotation: "Pulm", physician: "PN" },
      { week: 24, rotation: "MICU 1", physician: "KB" },
      { week: 24, rotation: "MICU 2", physician: "SP" },
      { week: 24, rotation: "AICU", physician: "JEK" },
      { week: 24, rotation: "LTAC", physician: "DPG" },
      { week: 24, rotation: "ROPH", physician: "WL" },
      { week: 24, rotation: "IP", physician: "PN" },
      { week: 24, rotation: "PFT", physician: "KJ" },
      { week: 25, rotation: "Pulm", physician: "MT" },
      { week: 25, rotation: "MICU 1", physician: "AK" },
      { week: 25, rotation: "MICU 2", physician: "JCR" },
      { week: 25, rotation: "AICU", physician: "MS" },
      { week: 25, rotation: "LTAC", physician: "JG" },
      { week: 25, rotation: "ROPH", physician: "KS" },
      { week: 25, rotation: "IP", physician: "JK" },
      { week: 25, rotation: "PFT", physician: "AT" },
      { week: 26, rotation: "Pulm", physician: "AT" },
      { week: 26, rotation: "MICU 1", physician: "JEK" },
      { week: 26, rotation: "MICU 2", physician: "PN" },
      { week: 26, rotation: "AICU", physician: "MV" },
      { week: 26, rotation: "LTAC", physician: "DPG" },
      { week: 26, rotation: "ROPH", physician: "WL" },
      { week: 26, rotation: "IP", physician: "EP" },
      { week: 26, rotation: "PFT", physician: "SF" },
      { week: 27, rotation: "Pulm", physician: "AK" },
      { week: 27, rotation: "MICU 1", physician: "EC" },
      { week: 27, rotation: "MICU 2", physician: "JN" },
      { week: 27, rotation: "AICU", physician: "SP" },
      { week: 27, rotation: "LTAC", physician: "DPG" },
      { week: 27, rotation: "ROPH", physician: "WL" },
      { week: 27, rotation: "IP", physician: "PN" },
      { week: 27, rotation: "PFT", physician: "MY" },
      { week: 28, rotation: "Pulm", physician: "JK" },
      { week: 28, rotation: "MICU 1", physician: "MS" },
      { week: 28, rotation: "MICU 2", physician: "MY" },
      { week: 28, rotation: "AICU", physician: "KJ" },
      { week: 28, rotation: "LTAC", physician: "KS" },
      { week: 28, rotation: "ROPH", physician: "MT" },
      { week: 28, rotation: "IP", physician: "JK" },
      { week: 28, rotation: "PFT", physician: "AT" },
      { week: 29, rotation: "Pulm", physician: "KB" },
      { week: 29, rotation: "MICU 1", physician: "PN" },
      { week: 29, rotation: "MICU 2", physician: "SF" },
      { week: 29, rotation: "AICU", physician: "BS" },
      { week: 29, rotation: "LTAC", physician: "DPG" },
      { week: 29, rotation: "ROPH", physician: "JG" },
      { week: 29, rotation: "IP", physician: "EP" },
      { week: 29, rotation: "PFT", physician: "KJ" },
      { week: 30, rotation: "Pulm", physician: "MY" },
      { week: 30, rotation: "MICU 1", physician: "AT" },
      { week: 30, rotation: "MICU 2", physician: "AK" },
      { week: 30, rotation: "AICU", physician: "JN" },
      { week: 30, rotation: "LTAC", physician: "MT" },
      { week: 30, rotation: "ROPH", physician: "WL" },
      { week: 30, rotation: "IP", physician: "PN" },
      { week: 30, rotation: "PFT", physician: "SF" },
      { week: 31, rotation: "Pulm", physician: "SF" },
      { week: 31, rotation: "MICU 1", physician: "MV" },
      { week: 31, rotation: "MICU 2", physician: "JEK" },
      { week: 31, rotation: "AICU", physician: "KS" },
      { week: 31, rotation: "LTAC", physician: "MS" },
      { week: 31, rotation: "ROPH", physician: "SP" },
      { week: 31, rotation: "IP", physician: "JK" },
      { week: 31, rotation: "PFT", physician: "AT" },
      { week: 32, rotation: "Pulm", physician: "KJ" },
      { week: 32, rotation: "MICU 1", physician: "PN" },
      { week: 32, rotation: "MICU 2", physician: "KB" },
      { week: 32, rotation: "AICU", physician: "AK" },
      { week: 32, rotation: "LTAC", physician: "DPG" },
      { week: 32, rotation: "ROPH", physician: "WL" },
      { week: 32, rotation: "IP", physician: "EP" },
      { week: 32, rotation: "PFT", physician: "SF" },
      { week: 33, rotation: "Pulm", physician: "MY" },
      { week: 33, rotation: "MICU 1", physician: "SP" },
      { week: 33, rotation: "MICU 2", physician: "MS" },
      { week: 33, rotation: "AICU", physician: "JEK" },
      { week: 33, rotation: "LTAC", physician: "AT" },
      { week: 33, rotation: "ROPH", physician: "KS" },
      { week: 33, rotation: "IP", physician: "PN" },
      { week: 33, rotation: "PFT", physician: "KJ" },
      { week: 34, rotation: "Pulm", physician: "MV" },
      { week: 34, rotation: "MICU 1", physician: "SF" },
      { week: 34, rotation: "MICU 2", physician: "MT" },
      { week: 34, rotation: "AICU", physician: "JG" },
      { week: 34, rotation: "LTAC", physician: "DPG" },
      { week: 34, rotation: "ROPH", physician: "WL" },
      { week: 34, rotation: "IP", physician: "JK" },
      { week: 34, rotation: "PFT", physician: "MY" },
      { week: 35, rotation: "Pulm", physician: "MS" },
      { week: 35, rotation: "MICU 1", physician: "KJ" },
      { week: 35, rotation: "MICU 2", physician: "KS" },
      { week: 35, rotation: "AICU", physician: "PN" },
      { week: 35, rotation: "LTAC", physician: "AK" },
      { week: 35, rotation: "ROPH", physician: "JEK" },
      { week: 35, rotation: "IP", physician: "EP" },
      { week: 35, rotation: "PFT", physician: "SF" },
      { week: 36, rotation: "Pulm", physician: "AT" },
      { week: 36, rotation: "MICU 1", physician: "EC" },
      { week: 36, rotation: "MICU 2", physician: "MT" },
      { week: 36, rotation: "AICU", physician: "SF" },
      { week: 36, rotation: "LTAC", physician: "DPG" },
      { week: 36, rotation: "ROPH", physician: "WL" },
      { week: 36, rotation: "IP", physician: "PN" },
      { week: 36, rotation: "PFT", physician: "AT" },
      { week: 37, rotation: "Pulm", physician: "JR" },
      { week: 37, rotation: "MICU 1", physician: "JCR" },
      { week: 37, rotation: "MICU 2", physician: "JG" },
      { week: 37, rotation: "AICU", physician: "SP" },
      { week: 37, rotation: "LTAC", physician: "MV" },
      { week: 37, rotation: "ROPH", physician: "JEK" },
      { week: 37, rotation: "IP", physician: "JK" },
      { week: 37, rotation: "PFT", physician: "KJ" },
      { week: 38, rotation: "Pulm", physician: "MT" },
      { week: 38, rotation: "MICU 1", physician: "AK" },
      { week: 38, rotation: "MICU 2", physician: "JG" },
      { week: 38, rotation: "AICU", physician: "MY" },
      { week: 38, rotation: "LTAC", physician: "KS" },
      { week: 38, rotation: "ROPH", physician: "MS" },
      { week: 38, rotation: "IP", physician: "PN" },
      { week: 38, rotation: "PFT", physician: "SF" },
      { week: 39, rotation: "Pulm", physician: "KJ" },
      { week: 39, rotation: "MICU 1", physician: "PN" },
      { week: 39, rotation: "MICU 2", physician: "AG" },
      { week: 39, rotation: "AICU", physician: "KB" },
      { week: 39, rotation: "LTAC", physician: "JEK" },
      { week: 39, rotation: "ROPH", physician: "SF" },
      { week: 39, rotation: "IP", physician: "EP" },
      { week: 39, rotation: "PFT", physician: "MY" },
      { week: 40, rotation: "Pulm", physician: "AK" },
      { week: 40, rotation: "MICU 1", physician: "MS" },
      { week: 40, rotation: "MICU 2", physician: "BM" },
      { week: 40, rotation: "AICU", physician: "MV" },
      { week: 40, rotation: "LTAC", physician: "DPG" },
      { week: 40, rotation: "ROPH", physician: "WL" },
      { week: 40, rotation: "IP", physician: "JK" },
      { week: 40, rotation: "PFT", physician: "SF" },
      { week: 41, rotation: "Pulm", physician: "SP" },
      { week: 41, rotation: "MICU 1", physician: "JCR" },
      { week: 41, rotation: "MICU 2", physician: "AT" },
      { week: 41, rotation: "AICU", physician: "JEK" },
      { week: 41, rotation: "LTAC", physician: "JG" },
      { week: 41, rotation: "ROPH", physician: "KS" },
      { week: 41, rotation: "IP", physician: "EP" },
      { week: 41, rotation: "PFT", physician: "KJ" },
      { week: 42, rotation: "Pulm", physician: "AK" },
      { week: 42, rotation: "MICU 1", physician: "KB" },
      { week: 42, rotation: "MICU 2", physician: "MV" },
      { week: 42, rotation: "AICU", physician: "KJ" },
      { week: 42, rotation: "LTAC", physician: "DPG" },
      { week: 42, rotation: "ROPH", physician: "WL" },
      { week: 42, rotation: "IP", physician: "PN" },
      { week: 42, rotation: "PFT", physician: "AT" },
      { week: 43, rotation: "Pulm", physician: "KS" },
      { week: 43, rotation: "MICU 1", physician: "KB" },
      { week: 43, rotation: "MICU 2", physician: "EC" },
      { week: 43, rotation: "AICU", physician: "MS" },
      { week: 43, rotation: "LTAC", physician: "PN" },
      { week: 43, rotation: "ROPH", physician: "MT" },
      { week: 43, rotation: "IP", physician: "JK" },
      { week: 43, rotation: "PFT", physician: "MY" },
      { week: 44, rotation: "Pulm", physician: "SF" },
      { week: 44, rotation: "MICU 1", physician: "JEK" },
      { week: 44, rotation: "MICU 2", physician: "SP" },
      { week: 44, rotation: "AICU", physician: "JG" },
      { week: 44, rotation: "LTAC", physician: "DPG" },
      { week: 44, rotation: "ROPH", physician: "WL" },
      { week: 44, rotation: "IP", physician: "EP" },
      { week: 44, rotation: "PFT", physician: "AT" },
      { week: 45, rotation: "Pulm", physician: "MY" },
      { week: 45, rotation: "MICU 1", physician: "KS" },
      { week: 45, rotation: "MICU 2", physician: "MT" },
      { week: 45, rotation: "AICU", physician: "JG" },
      { week: 45, rotation: "LTAC", physician: "AT" },
      { week: 45, rotation: "ROPH", physician: "MS" },
      { week: 45, rotation: "IP", physician: "JK" },
      { week: 45, rotation: "PFT", physician: "SF" },
      { week: 46, rotation: "Pulm", physician: "PN" },
      { week: 46, rotation: "MICU 1", physician: "MV" },
      { week: 46, rotation: "MICU 2", physician: "JEK" },
      { week: 46, rotation: "AICU", physician: "EC" },
      { week: 46, rotation: "LTAC", physician: "DPG" },
      { week: 46, rotation: "ROPH", physician: "WL" },
      { week: 46, rotation: "IP", physician: "PN" },
      { week: 46, rotation: "PFT", physician: "KJ" },
      { week: 47, rotation: "Pulm", physician: "SP" },
      { week: 47, rotation: "MICU 1", physician: "KJ" },
      { week: 47, rotation: "MICU 2", physician: "KS" },
      { week: 47, rotation: "AICU", physician: "MT" },
      { week: 47, rotation: "LTAC", physician: "MS" },
      { week: 47, rotation: "ROPH", physician: "SF" },
      { week: 47, rotation: "IP", physician: "EP" },
      { week: 47, rotation: "PFT", physician: "MY" },
      { week: 48, rotation: "Pulm", physician: "JR" },
      { week: 48, rotation: "MICU 1", physician: "MY" },
      { week: 48, rotation: "MICU 2", physician: "AG" },
      { week: 48, rotation: "AICU", physician: "SP" },
      { week: 48, rotation: "LTAC", physician: "DPG" },
      { week: 48, rotation: "ROPH", physician: "WL" },
      { week: 48, rotation: "IP", physician: "PN" },
      { week: 48, rotation: "PFT", physician: "AT" },
      { week: 49, rotation: "Pulm", physician: "MT" },
      { week: 49, rotation: "MICU 1", physician: "JEK" },
      { week: 49, rotation: "MICU 2", physician: "PN" },
      { week: 49, rotation: "AICU", physician: "JN" },
      { week: 49, rotation: "LTAC", physician: "AK" },
      { week: 49, rotation: "ROPH", physician: "MV" },
      { week: 49, rotation: "IP", physician: "JK" },
      { week: 49, rotation: "PFT", physician: "KJ" },
      { week: 50, rotation: "Pulm", physician: "KJ" },
      { week: 50, rotation: "MICU 1", physician: "KS" },
      { week: 50, rotation: "MICU 2", physician: "AK" },
      { week: 50, rotation: "AICU", physician: "JG" },
      { week: 50, rotation: "LTAC", physician: "DPG" },
      { week: 50, rotation: "ROPH", physician: "WL" },
      { week: 50, rotation: "IP", physician: "EP" },
      { week: 50, rotation: "PFT", physician: "SF" },
      { week: 51, rotation: "Pulm", physician: "MV" },
      { week: 51, rotation: "MICU 1", physician: "AT" },
      { week: 51, rotation: "MICU 2", physician: "MS" },
      { week: 51, rotation: "AICU", physician: "JG" },
      { week: 51, rotation: "LTAC", physician: "MT" },
      { week: 51, rotation: "ROPH", physician: "SF" },
      { week: 51, rotation: "IP", physician: "JK" },
      { week: 51, rotation: "PFT", physician: "MY" },
      { week: 52, rotation: "Pulm", physician: "PN" },
      { week: 52, rotation: "MICU 1", physician: "SP" },
      { week: 52, rotation: "MICU 2", physician: "AK" },
      { week: 52, rotation: "AICU", physician: "JEK" },
      { week: 52, rotation: "LTAC", physician: "DPG" },
      { week: 52, rotation: "ROPH", physician: "WL" },
      { week: 52, rotation: "IP", physician: "PN" },
      { week: 52, rotation: "PFT", physician: "AT" },
      { week: 53, rotation: "Pulm", physician: "KS" },
      { week: 53, rotation: "MICU 1", physician: "KB" },
      { week: 53, rotation: "MICU 2", physician: "EC" },
      { week: 53, rotation: "AICU", physician: "MV" },
      { week: 53, rotation: "LTAC", physician: "DPG" },
      { week: 53, rotation: "ROPH", physician: "WL" },
      { week: 53, rotation: "IP", physician: "EP" },
      { week: 53, rotation: "PFT", physician: "KJ" },
    ];

    // Create assignments
    let assignmentsCreated = 0;
    for (const assignment of assignmentData) {
      const weekId = weekIdMap.get(assignment.week);
      const rotationId = rotationIdMap.get(assignment.rotation);
      const physicianId = physicianIdMap.get(assignment.physician);

      if (weekId && rotationId && physicianId) {
        await ctx.db.insert("assignments", {
          masterCalendarId,
          weekId,
          rotationId,
          physicianId,
          assignmentSource: "import",
          assignedAt: Date.now(),
        });
        assignmentsCreated++;
      }
    }

    return {
      fiscalYearId,
      physiciansCreated: physicians.length,
      rotationsCreated: rotations.length,
      weeksCreated: weekData.length,
      masterCalendarId,
      assignmentsCreated,
    };
  },
});
